### ISSUE TITLE
Allow multiple tables per file

### ISSUE THREAD

**Issue by whatyoubendoing** [theiconic/fixtures#8]
Currently you can only have 1 fixture per table per file ie would be nice to define multiple fixtures for tables per file.  ie 

```yml 

---
customer:
  -
    id_customer: 1
    email: superman@example.com
    first_name: Clark
    last_name: Kent
    password: $2y$14$GtiB0uhr5ptz2BAfC7xMwO2.lqrcryWj09lkvx0YlehoaIVxlDaVq
    is_testaccount: 1
    fk_language: 1
newsletter_subscription:
  -
    fk_customer: 1
    email: superman@example.com
    unsubscribe_key: d71fe2bf979e1fecf54e98ced3fe5bb5
    status: subscribed
    custom_fields: ''
  -
    email: batman@example.com
    unsubscribe_key: a1ed93f0dc7ae7fb25eecd09cf5fd186
    status: subscribed
    custom_fields: ''
```
